// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/superorbital/cludo/models"
)

// ListRolesReader is a Reader for the ListRoles structure.
type ListRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListRolesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListRolesOK creates a ListRolesOK with default headers values
func NewListRolesOK() *ListRolesOK {
	return &ListRolesOK{}
}

/* ListRolesOK describes a response with status code 200, with default header values.

OK
*/
type ListRolesOK struct {
	Payload string
}

func (o *ListRolesOK) Error() string {
	return fmt.Sprintf("[GET /role][%d] listRolesOK  %+v", 200, o.Payload)
}
func (o *ListRolesOK) GetPayload() string {
	return o.Payload
}

func (o *ListRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRolesBadRequest creates a ListRolesBadRequest with default headers values
func NewListRolesBadRequest() *ListRolesBadRequest {
	return &ListRolesBadRequest{}
}

/* ListRolesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListRolesBadRequest struct {
	Payload string
}

func (o *ListRolesBadRequest) Error() string {
	return fmt.Sprintf("[GET /role][%d] listRolesBadRequest  %+v", 400, o.Payload)
}
func (o *ListRolesBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ListRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRolesDefault creates a ListRolesDefault with default headers values
func NewListRolesDefault(code int) *ListRolesDefault {
	return &ListRolesDefault{
		_statusCode: code,
	}
}

/* ListRolesDefault describes a response with status code -1, with default header values.

generic error response
*/
type ListRolesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list roles default response
func (o *ListRolesDefault) Code() int {
	return o._statusCode
}

func (o *ListRolesDefault) Error() string {
	return fmt.Sprintf("[GET /role][%d] list-roles default  %+v", o._statusCode, o.Payload)
}
func (o *ListRolesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListRolesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
