// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new environment API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for environment API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GenerateEnvironment(params *GenerateEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GenerateEnvironmentOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GenerateEnvironment generates a temporary environment

  Generate a temporary environment (set of environment variables)
*/
func (a *Client) GenerateEnvironment(params *GenerateEnvironmentParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GenerateEnvironmentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGenerateEnvironmentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "generate-environment",
		Method:             "POST",
		PathPattern:        "/environment",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GenerateEnvironmentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GenerateEnvironmentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GenerateEnvironmentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
