// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/superorbital/cludo/models"
)

// NewGenerateEnvironmentParams creates a new GenerateEnvironmentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateEnvironmentParams() *GenerateEnvironmentParams {
	return &GenerateEnvironmentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateEnvironmentParamsWithTimeout creates a new GenerateEnvironmentParams object
// with the ability to set a timeout on a request.
func NewGenerateEnvironmentParamsWithTimeout(timeout time.Duration) *GenerateEnvironmentParams {
	return &GenerateEnvironmentParams{
		timeout: timeout,
	}
}

// NewGenerateEnvironmentParamsWithContext creates a new GenerateEnvironmentParams object
// with the ability to set a context for a request.
func NewGenerateEnvironmentParamsWithContext(ctx context.Context) *GenerateEnvironmentParams {
	return &GenerateEnvironmentParams{
		Context: ctx,
	}
}

// NewGenerateEnvironmentParamsWithHTTPClient creates a new GenerateEnvironmentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateEnvironmentParamsWithHTTPClient(client *http.Client) *GenerateEnvironmentParams {
	return &GenerateEnvironmentParams{
		HTTPClient: client,
	}
}

/* GenerateEnvironmentParams contains all the parameters to send to the API endpoint
   for the generate environment operation.

   Typically these are written to a http.Request.
*/
type GenerateEnvironmentParams struct {

	/* Body.

	   Temporary Environment Request definition
	*/
	Body *models.ModelsEnvironmentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate environment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateEnvironmentParams) WithDefaults() *GenerateEnvironmentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate environment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateEnvironmentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate environment params
func (o *GenerateEnvironmentParams) WithTimeout(timeout time.Duration) *GenerateEnvironmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate environment params
func (o *GenerateEnvironmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate environment params
func (o *GenerateEnvironmentParams) WithContext(ctx context.Context) *GenerateEnvironmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate environment params
func (o *GenerateEnvironmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate environment params
func (o *GenerateEnvironmentParams) WithHTTPClient(client *http.Client) *GenerateEnvironmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate environment params
func (o *GenerateEnvironmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate environment params
func (o *GenerateEnvironmentParams) WithBody(body *models.ModelsEnvironmentRequest) *GenerateEnvironmentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate environment params
func (o *GenerateEnvironmentParams) SetBody(body *models.ModelsEnvironmentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateEnvironmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
