apiVersion: apps/v1
kind: Deployment
metadata:
  name: cludod
  labels:
    app: cludod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cludod
  template:
    metadata:
      labels:
        app: cludod
    spec:
      containers:
      - name: cludod
        image: superorbital/cludod:latest
        resources:
          requests:
            memory: "2M"
            cpu: "250m"
          limits:
            memory: "128M"
            cpu: "1"
        command:
        - cludod
        - --scheme=http
        - --host=0.0.0.0
        - --port=80
        ports:
            - name: http
              containerPort: 80
              protocol: TCP
        livenessProbe:
          httpGet:
            path: /v1/health
            port: http
        readinessProbe:
          httpGet:
            path: /v1/health
            port: http
        volumeMounts:
        - name: config
          mountPath: "/etc/cludod"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: cludod-config
