apiVersion: v1
kind: Service
metadata:
  name: cludod
spec:
  externalTrafficPolicy: Local
  selector:
    app: cludod
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
