version: "3.7"
services:
  cludod:
    build:
      context: ./
      dockerfile: ./Dockerfile.cludod
    image: superorbital/cludod:local
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/.cludod/cludod.yaml:/etc/cludod/cludod.yaml
    stdin_open: true
    environment:
      - PORT=8080
