swagger: '2.0'
basePath: "/v1"
consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
info:
  description: cludod - Cloud Sudo Server
  title: cludod
  contact:
    name: SuperOrbital
    url: http://superorbital.io/
    email: info@superorbital.io
  version: 1.0.0
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-CLUDO-KEY
definitions:
  models.EnvironmentRequest:
    type: object
    properties:
      target:
        description: The requested target for the request
        type: string
  models.EnvironmentResponse:
    type: object
    properties:
      bundle:
        $ref: "#/definitions/models.EnvironmentBundle"
  models.EnvironmentBundle:
    type: object
    additionalProperties:
      type: string
    example:
      ENV_VAR_1: Hello!
      ENV_VAR_2: Bonjour!
  models.RoleIDsResponse:
    type: object
    properties:
      roles:
        type: array
        items:
          type: string
  models.HealthResponse:
    type: object
    properties:
      status:
        type: boolean
      version:
        type: string
  models.Principal:
    type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  "/health":
    get:
      description: Reports server status
      tags:
      - system
      summary: Reports server status
      operationId: health
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/models.HealthResponse"
        '400':
          description: Bad Request
          schema:
            type: string
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  "/role":
    get:
      description: List all roles available to current user
      security:
      - APIKeyHeader: []
      tags:
      - role
      summary: List all roles
      operationId: list-roles
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/models.RoleIDsResponse"
        '400':
          description: Bad Request
          schema:
            type: string
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  "/environment":
    post:
      description: Generate a temporary environment (set of environment variables)
      security:
      - APIKeyHeader: []
      tags:
      - environment
      summary: Generate a temporary environment
      operationId: generate-environment
      parameters:
      - description: Temporary Environment Request definition
        name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/models.EnvironmentRequest"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/models.EnvironmentResponse"
        '400':
          description: Bad Request
          schema:
            type: string
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
