// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/superorbital/cludo/models"
)

// HealthReader is a Reader for the Health structure.
type HealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewHealthBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewHealthDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHealthOK creates a HealthOK with default headers values
func NewHealthOK() *HealthOK {
	return &HealthOK{}
}

/* HealthOK describes a response with status code 200, with default header values.

OK
*/
type HealthOK struct {
	Payload *models.ModelsHealthResponse
}

func (o *HealthOK) Error() string {
	return fmt.Sprintf("[GET /health][%d] healthOK  %+v", 200, o.Payload)
}
func (o *HealthOK) GetPayload() *models.ModelsHealthResponse {
	return o.Payload
}

func (o *HealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsHealthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHealthBadRequest creates a HealthBadRequest with default headers values
func NewHealthBadRequest() *HealthBadRequest {
	return &HealthBadRequest{}
}

/* HealthBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type HealthBadRequest struct {
	Payload string
}

func (o *HealthBadRequest) Error() string {
	return fmt.Sprintf("[GET /health][%d] healthBadRequest  %+v", 400, o.Payload)
}
func (o *HealthBadRequest) GetPayload() string {
	return o.Payload
}

func (o *HealthBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHealthDefault creates a HealthDefault with default headers values
func NewHealthDefault(code int) *HealthDefault {
	return &HealthDefault{
		_statusCode: code,
	}
}

/* HealthDefault describes a response with status code -1, with default header values.

generic error response
*/
type HealthDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the health default response
func (o *HealthDefault) Code() int {
	return o._statusCode
}

func (o *HealthDefault) Error() string {
	return fmt.Sprintf("[GET /health][%d] health default  %+v", o._statusCode, o.Payload)
}
func (o *HealthDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *HealthDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
