apiVersion: apps/v1
kind: Deployment
metadata:
  name: cludod-deployment
  labels:
    app: cludod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cludod
  template:
    metadata:
      labels:
        app: cludod
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: cludod
        image: superorbital/cludod:latest
        command:
        - cludod
        - --scheme=http
        - --host=0.0.0.0
        - --port=80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/etc/cludod"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: cludod-config
