// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"log"

	"github.com/superorbital/cludo/client"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
)

// debug flag indicating that cli should output debug logs
var debug bool

// logDebugf writes debug log to stdout
func logDebugf(format string, v ...interface{}) {
	if !debug {
		return
	}
	log.Printf(format, v...)
}

// makeClient constructs a client object
func makeClient(cmd *cobra.Command, args []string) (*client.CludoAPI, error) {
	hostname, err := cmd.Flags().GetString("hostname")
	if err != nil {
		return nil, err
	}
	scheme, err := cmd.Flags().GetString("scheme")
	if err != nil {
		return nil, err
	}

	r := httptransport.New(hostname, client.DefaultBasePath, []string{scheme})
	// set custom producer and consumer to use the default ones

	r.Consumers["application/json"] = runtime.JSONConsumer()

	r.Producers["application/json"] = runtime.JSONProducer()

	appCli := client.New(r, strfmt.Default)
	logDebugf("Server url: %v://%v", scheme, hostname)
	return appCli, nil
}

// MakeRootCmd returns the root cmd
func MakeRootCmd() (*cobra.Command, error) {
	rootCmd := &cobra.Command{
		Use: "CludoAPI",
	}
	// register basic flags
	rootCmd.PersistentFlags().String("hostname", client.DefaultHost, "hostname of the service")
	rootCmd.PersistentFlags().String("scheme", client.DefaultSchemes[0], fmt.Sprintf("Choose from: %v", client.DefaultSchemes))

	// configure debug flag
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "output debug logs")

	// register security flags
	// add all operation groups
	operationGroupEnvironmentCmd, err := makeOperationGroupEnvironmentCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(operationGroupEnvironmentCmd)

	operationGroupRoleCmd, err := makeOperationGroupRoleCmd()
	if err != nil {
		return nil, err
	}
	rootCmd.AddCommand(operationGroupRoleCmd)

	return rootCmd, nil
}

func makeOperationGroupEnvironmentCmd() (*cobra.Command, error) {
	operationGroupEnvironmentCmd := &cobra.Command{
		Use:  "environment",
		Long: ``,
	}

	operationGenerateEnvironmentCmd, err := makeOperationEnvironmentGenerateEnvironmentCmd()
	if err != nil {
		return nil, err
	}
	operationGroupEnvironmentCmd.AddCommand(operationGenerateEnvironmentCmd)

	return operationGroupEnvironmentCmd, nil
}
func makeOperationGroupRoleCmd() (*cobra.Command, error) {
	operationGroupRoleCmd := &cobra.Command{
		Use:  "role",
		Long: ``,
	}

	operationListRolesCmd, err := makeOperationRoleListRolesCmd()
	if err != nil {
		return nil, err
	}
	operationGroupRoleCmd.AddCommand(operationListRolesCmd)

	return operationGroupRoleCmd, nil
}
