// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/superorbital/cludo/client/environment"
	"github.com/superorbital/cludo/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationEnvironmentGenerateEnvironmentCmd returns a cmd to handle operation generateEnvironment
func makeOperationEnvironmentGenerateEnvironmentCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "generate-environment",
		Short: `Generate a temporary environment (set of environment variables)`,
		RunE:  runOperationEnvironmentGenerateEnvironment,
	}

	if err := registerOperationEnvironmentGenerateEnvironmentParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEnvironmentGenerateEnvironment uses cmd flags to call endpoint api
func runOperationEnvironmentGenerateEnvironment(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := environment.NewGenerateEnvironmentParams()
	if err, _ := retrieveOperationEnvironmentGenerateEnvironmentBodyFlag(params, "", cmd); err != nil {
		return err
	}
	// make request and then print result
	if err := printOperationEnvironmentGenerateEnvironmentResult(appCli.Environment.GenerateEnvironment(params)); err != nil {
		return err
	}
	return nil
}

func retrieveOperationEnvironmentGenerateEnvironmentBodyFlag(m *environment.GenerateEnvironmentParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.ModelsEnvironmentRequest{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.ModelsEnvironmentRequest: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.ModelsEnvironmentRequest{}
	}
	err, added := retrieveModelsEnvironmentRequestFlags(bodyValueModel, "modelsEnvironmentRequest", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	bodyValueDebugBytes, err := json.Marshal(m.Body)
	if err != nil {
		return err, false
	}
	logDebugf("Body payload: %v", string(bodyValueDebugBytes))
	return nil, retAdded
}

// printOperationEnvironmentGenerateEnvironmentResult prints output to stdout
func printOperationEnvironmentGenerateEnvironmentResult(resp0 *environment.GenerateEnvironmentOK, respErr error) error {
	if respErr != nil {

		var iResp interface{} = respErr
		defaultResp, ok := iResp.(*environment.GenerateEnvironmentDefault)
		if !ok {
			return respErr
		}
		if defaultResp.Payload != nil {
			msgStr, err := json.Marshal(defaultResp.Payload)
			if err != nil {
				return err
			}
			fmt.Println(string(msgStr))
			return nil
		}

		return respErr
	}

	if resp0.Payload != nil {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return err
		}
		fmt.Println(string(msgStr))
	}

	return nil
}

// registerOperationEnvironmentGenerateEnvironmentParamFlags registers all flags needed to fill params
func registerOperationEnvironmentGenerateEnvironmentParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEnvironmentGenerateEnvironmentBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEnvironmentGenerateEnvironmentBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	exampleBodyStr, err := json.Marshal(&models.ModelsEnvironmentRequest{})
	if err != nil {
		return err
	}
	_ = cmd.PersistentFlags().String(bodyFlagName, "", fmt.Sprintf("Optional json string for [body] of form %v.Temporary Environment Request definition", string(exampleBodyStr)))

	// add flags for body
	if err := registerModelsEnvironmentRequestFlags("modelsEnvironmentRequest", cmd); err != nil {
		return err
	}

	return nil
}
