// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Cludo API
//
//  Cludo - Cloud Sudo
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  Contact: SuperOrbital<info@superorbital.io> http://superorbital.io/
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
