// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListRolesHandlerFunc turns a function with the right signature into a list roles handler
type ListRolesHandlerFunc func(ListRolesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListRolesHandlerFunc) Handle(params ListRolesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListRolesHandler interface for that can handle valid list roles params
type ListRolesHandler interface {
	Handle(ListRolesParams, interface{}) middleware.Responder
}

// NewListRoles creates a new http.Handler for the list roles operation
func NewListRoles(ctx *middleware.Context, handler ListRolesHandler) *ListRoles {
	return &ListRoles{Context: ctx, Handler: handler}
}

/* ListRoles swagger:route GET /role role listRoles

List all roles

List all roles available to current user

*/
type ListRoles struct {
	Context *middleware.Context
	Handler ListRolesHandler
}

func (o *ListRoles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListRolesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
