// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/superorbital/cludo/models"
)

// ListRolesOKCode is the HTTP code returned for type ListRolesOK
const ListRolesOKCode int = 200

/*ListRolesOK OK

swagger:response listRolesOK
*/
type ListRolesOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewListRolesOK creates ListRolesOK with default headers values
func NewListRolesOK() *ListRolesOK {

	return &ListRolesOK{}
}

// WithPayload adds the payload to the list roles o k response
func (o *ListRolesOK) WithPayload(payload string) *ListRolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list roles o k response
func (o *ListRolesOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListRolesBadRequestCode is the HTTP code returned for type ListRolesBadRequest
const ListRolesBadRequestCode int = 400

/*ListRolesBadRequest Bad Request

swagger:response listRolesBadRequest
*/
type ListRolesBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewListRolesBadRequest creates ListRolesBadRequest with default headers values
func NewListRolesBadRequest() *ListRolesBadRequest {

	return &ListRolesBadRequest{}
}

// WithPayload adds the payload to the list roles bad request response
func (o *ListRolesBadRequest) WithPayload(payload string) *ListRolesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list roles bad request response
func (o *ListRolesBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRolesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListRolesDefault generic error response

swagger:response listRolesDefault
*/
type ListRolesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListRolesDefault creates ListRolesDefault with default headers values
func NewListRolesDefault(code int) *ListRolesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListRolesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list roles default response
func (o *ListRolesDefault) WithStatusCode(code int) *ListRolesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list roles default response
func (o *ListRolesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list roles default response
func (o *ListRolesDefault) WithPayload(payload *models.Error) *ListRolesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list roles default response
func (o *ListRolesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRolesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
