// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/superorbital/cludo/models"
)

// HealthOKCode is the HTTP code returned for type HealthOK
const HealthOKCode int = 200

/*HealthOK OK

swagger:response healthOK
*/
type HealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelsHealthResponse `json:"body,omitempty"`
}

// NewHealthOK creates HealthOK with default headers values
func NewHealthOK() *HealthOK {

	return &HealthOK{}
}

// WithPayload adds the payload to the health o k response
func (o *HealthOK) WithPayload(payload *models.ModelsHealthResponse) *HealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health o k response
func (o *HealthOK) SetPayload(payload *models.ModelsHealthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HealthBadRequestCode is the HTTP code returned for type HealthBadRequest
const HealthBadRequestCode int = 400

/*HealthBadRequest Bad Request

swagger:response healthBadRequest
*/
type HealthBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewHealthBadRequest creates HealthBadRequest with default headers values
func NewHealthBadRequest() *HealthBadRequest {

	return &HealthBadRequest{}
}

// WithPayload adds the payload to the health bad request response
func (o *HealthBadRequest) WithPayload(payload string) *HealthBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health bad request response
func (o *HealthBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*HealthDefault generic error response

swagger:response healthDefault
*/
type HealthDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHealthDefault creates HealthDefault with default headers values
func NewHealthDefault(code int) *HealthDefault {
	if code <= 0 {
		code = 500
	}

	return &HealthDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the health default response
func (o *HealthDefault) WithStatusCode(code int) *HealthDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the health default response
func (o *HealthDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the health default response
func (o *HealthDefault) WithPayload(payload *models.Error) *HealthDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health default response
func (o *HealthDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
