// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GenerateEnvironmentHandlerFunc turns a function with the right signature into a generate environment handler
type GenerateEnvironmentHandlerFunc func(GenerateEnvironmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GenerateEnvironmentHandlerFunc) Handle(params GenerateEnvironmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GenerateEnvironmentHandler interface for that can handle valid generate environment params
type GenerateEnvironmentHandler interface {
	Handle(GenerateEnvironmentParams, interface{}) middleware.Responder
}

// NewGenerateEnvironment creates a new http.Handler for the generate environment operation
func NewGenerateEnvironment(ctx *middleware.Context, handler GenerateEnvironmentHandler) *GenerateEnvironment {
	return &GenerateEnvironment{Context: ctx, Handler: handler}
}

/* GenerateEnvironment swagger:route POST /environment environment generateEnvironment

Generate a temporary environment

Generate a temporary environment (set of environment variables)

*/
type GenerateEnvironment struct {
	Context *middleware.Context
	Handler GenerateEnvironmentHandler
}

func (o *GenerateEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGenerateEnvironmentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
