name: cludo CI
on: [ push]
jobs:
  cludo-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5' # The Go version to download and use.
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: List available build platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/ahmetb/govvv@latest
          go install github.com/mitchellh/gox@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Detect Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Run Tests
        run: make test
      - name: Build Binaries
        run: make build
      - name: Build and Push Container Images
        run: make docker-build-push
        env:
          BUILDKIT_PROGRESS: plain
          PR_NUM: ${{ steps.findPr.outputs.pr }}
