name: cludo PR Closure Cleanup
on:
  pull_request:
    types: [closed]
jobs:
  pr-closure-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5' # The Go version to download and use.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Install Docker hub-tool
        # Migrate back to the official release once something like these changes are merged:
        # https://github.com/docker/hub-tool/pull/198
        # https://github.com/docker/hub-tool/issues/58#issuecomment-1006058934
        run: |
          #curl -sO $(curl -sL https://api.github.com/repos/docker/hub-tool/releases/latest | jq -r '.assets[].browser_download_url' | grep linux-amd64.tar.gz) | tar -xz  -C /usr/bin
          git clone https://github.com/docker/hub-tool.git
          cd hub-tool
          git checkout c9cb0ac822ad431a252d462d80ab0dcc21d49e6f
          cat << "EOF" > fixes.patch
          diff -ur hub-tool/internal/commands/tag/rm.go hub-tool-envlogin/internal/commands/tag/rm.go
          --- hub-tool/internal/commands/tag/rm.go	2022-01-05 13:04:09.000000000 -0800
          +++ hub-tool-envlogin/internal/commands/tag/rm.go	2022-01-05 13:04:58.000000000 -0800
          @@ -96,7 +96,12 @@
           	}
          
           	if err := hubClient.RemoveTag(reference.FamiliarName(ref), ref.Tag()); err != nil {
          -		return err
          +		if strings.Contains(err.Error(), "404 NOT FOUND") {
          +			fmt.Fprintln(streams.Out(), "Not Found", image)
          +			return nil
          +		} else {
          +			return err
          +		}
           	}
           	fmt.Fprintln(streams.Out(), "Deleted", image)
           	return nil
          diff -ur hub-tool/internal/login/login.go hub-tool-envlogin/internal/login/login.go
          --- hub-tool/internal/login/login.go	2022-01-05 13:04:09.000000000 -0800
          +++ hub-tool-envlogin/internal/login/login.go	2022-01-05 10:18:07.000000000 -0800
          @@ -40,14 +40,20 @@
           func RunLogin(ctx context.Context, streams command.Streams, hubClient *hub.Client, store credentials.Store, candidateUsername string) error {
           	username := candidateUsername
           	if username == "" {
          +		username = os.Getenv("DOCKER_USERNAME")
          +	}
          +	if username == "" {
           		var err error
           		if username, err = readClearText(ctx, streams, "Username: "); err != nil {
           			return err
           		}
           	}
          -	password, err := readPassword(streams)
          -	if err != nil {
          -		return err
          +	password := os.Getenv("DOCKER_PASSWORD")
          +	if password == "" {
          +		var err error
          +		if password, err = readPassword(streams); err != nil {
          +			return err
          +		}
           	}
          
           	token, refreshToken, err := Login(ctx, streams, hubClient, username, password)
          EOF
          patch -s -p1 < ./fixes.patch
          make
          sudo mv bin/hub-tool /usr/bin/hub-tool
          chmod a+rx /usr/bin/hub-tool
      - name: Remove PR container image via hub-tool
        run: |
          /usr/bin/hub-tool login
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development.git-PR-${PR_NUM}
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development.git-PR-${PR_NUM}
          # These are not supposed to exist (but at the moment, might)
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development.git-PR-
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development.git-PR-
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development
        env:
          BUILDKIT_PROGRESS: plain
          PR_NUM: ${{ github.event.pull_request.number }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          # It appears that we MUST use our real password (versus a token) for tag deletion to work :(
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
