name: cludo PR Closure Cleanup
on:
  pull_request:
    types: [closed]
jobs:
  pr-closure-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker hub-tool
        # Migrate back to the official release once something like these changes are merged:
        # https://github.com/docker/hub-tool/pull/198
        # https://github.com/docker/hub-tool/issues/58#issuecomment-1006058934
        run: |
          curl -sL https://github.com/superorbital/docker-hub-tool/releases/download/2022-01-06-patched/hub-tool_linux_amd64 -o /usr/bin/hub-tool
          chmod a+rx /usr/bin/hub-tool
      - name: Remove PR container image via hub-tool
        run: |
          /usr/bin/hub-tool login
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development.git-PR-${PR_NUM}
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development.git-PR-${PR_NUM}
          # These are not supposed to exist (but at the moment, might)
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development.git-PR-
          /usr/bin/hub-tool tag rm -f superorbital/cludo:development
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development.git-PR-
          /usr/bin/hub-tool tag rm -f superorbital/cludod:development
        env:
          BUILDKIT_PROGRESS: plain
          PR_NUM: ${{ github.event.pull_request.number }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          # It appears that we MUST use our real password (versus a token) for tag deletion to work :(
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
