// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsAWSPrincipalRole models a w s principal role
//
// swagger:model models.AWSPrincipalRole
type ModelsAWSPrincipalRole struct {

	// access key id
	AccessKeyID string `json:"access_key_id,omitempty"`

	// arn
	Arn string `json:"arn,omitempty"`

	// secret access key
	SecretAccessKey string `json:"secret_access_key,omitempty"`

	// session duration
	SessionDuration string `json:"session_duration,omitempty"`
}

// Validate validates this models a w s principal role
func (m *ModelsAWSPrincipalRole) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models a w s principal role based on context it is used
func (m *ModelsAWSPrincipalRole) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsAWSPrincipalRole) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsAWSPrincipalRole) UnmarshalBinary(b []byte) error {
	var res ModelsAWSPrincipalRole
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
