// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ModelsEnvironmentBundle models environment bundle
// Example: {"ENV_VAR_1":"Hello!","ENV_VAR_2":"Bonjour!"}
//
// swagger:model models.EnvironmentBundle
type ModelsEnvironmentBundle map[string]string

// Validate validates this models environment bundle
func (m ModelsEnvironmentBundle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models environment bundle based on context it is used
func (m ModelsEnvironmentBundle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
