// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ModelsPrincipal models principal
//
// swagger:model models.Principal
type ModelsPrincipal string

// Validate validates this models principal
func (m ModelsPrincipal) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models principal based on context it is used
func (m ModelsPrincipal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
